# Generated by Django 4.1.2 on 2022-11-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
