# Generated by Django 4.1.2 on 2022-11-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
